ALTER TABLE "RequirementAttachment"
ADD COLUMN "isQualified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "qualifiedAt" TIMESTAMP(3),
ADD COLUMN "qualifyNote" TEXT,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
